### ISSUE TITLE
Service failing to start

### ISSUE THREAD

**Issue by cani-venatici** [daveriedstra/draggy#5] opened 2021-02-28 14:51 UTC
Hi,

is the error due to an unsupported device or?

![image](https://user-images.githubusercontent.com/30556695/109422630-a56bbf00-79dc-11eb-80ff-8c9913bcc095.png)

**Comment by daveriedstra** [comment] 2021-02-28 15:18
The device *should* be fine, it runs with a different Wacom tablet (which I unfortunately don't have available to test with).

Judging by the last line, it looks like it works when started directly and that the issue is with the systemd service. Can you confirm whether it works when started from the command line?

**Comment by cani-venatici** [comment] 2021-02-28 17:09
as in if 3 or 4 fingers drag works when run with -d /dev/input...? no unfortunately it doesn't :<

**Comment by daveriedstra** [comment] 2021-03-03 20:45
I see. I will look into this, but things are busy for me and it will be quite difficult without the hardware at hand.

**Comment by daveriedstra** [comment] 2022-04-30 22:16
Hi again. Sorry for the long wait. I was finally reunited with my tablet and managed to fix this. My tablet is the Wacom Intuos PT S Finger, similar to yours, so it should hopefully work for yours as well (do let me know if you get a chance).

The changes might take some time to show up here since this is a mirror, the original is [here](https://gitlab.com/daveriedstra/draggy)

The details are a bit silly: basically to perform a three-finger drag, the "surrogate" device sends a click on a left mouse button. When draggy makes the surrogate it just clones the specified input device. If that device doesn't have a left button (as our tablets don't) then evdev / UInput don't do anything with the surrogate's button click. The way around it is to explicitly add the left button capability to the surrogate device, but unfortunately simply creating a device with the required capabilities (as opposed to cloning a physical one) wasn't working -- until I stumbled upon https://github.com/gvalkov/python-evdev/issues/60#issuecomment-238791290 which managed to solve everything.

I'm going to close this issue for now, if it's still not working let me know and I'll re-open it (though in that case I *really* don't know what I'll be able to do...)

**Closed as completed** 2022-04-30 22:16 UTC
